server:
  port: 7777

spring:
  profiles:
    active: ${ENV:dev}
  main:
    web-application-type=none:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://mysql.railway.internal:3306/railway
#    username: root
#    password: nJeGhlsXRnEwqObtRYnhDNQOFbcLGviU
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#server:
#  port: 7777
