server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://root:caerLbhXCnGpvZpMRAYDAceQLBVhuEBL@mysql.railway.internal:3306/railway  # Correct JDBC URL without credentials        # Specify the password here
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
