spring:
  datasource:
    url: mysql://root:nJeGhlsXRnEwqObtRYnhDNQOFbcLGviU@mysql.railway.internal:3306/railway
    username: root
    password: nJeGhlsXRnEwqObtRYnhDNQOFbcLGviU
    driver-class-name: com.mysql.cj.jdbc.Driver
